name: build

on:
  push:
  pull_request:
    branches: [ develop, production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Use Deno v2.x
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Run script
      run: |
        deno task start
      env:
        CI: true
